export const AdminRoutes = {
  DefaultRoute: '/',
  adminRoute: '/admin',
  AdminSignin: '/admin/signin',
  Dashboard: '/admin/dashboard',
  Admins: '/admin/admins',
  AdminDetails: '/admin/admin-details/:adminId',
  Currencies: '/admin/currencies',
  Languages: '/admin/languages',
  CreateCurrencies: '/admin/create-currencies',
  EditCurrency: '/admin/edit-currency/:currencyId',
  EditTheme: '/admin/edit-theme/:themeId',
  CreateTheme: '/admin/create-theme',
  CMS: '/admin/cms',
  Users: '/admin/users',
  UserDetails: '/admin/user-details/:userId',
  CreateCurrency: '/admin/create-currency',
  AffiliateDetail: '/admin/affiliate-details/:affiliateId',
  AddSubCategoryGames: '/admin/add-games/:masterGameSubCategoryId',
  CMSDetail: '/admin/cms-details/:cmsPageId',
  CasinoProviders: '/admin/casino-management/casino-providers',
  CasinoGames: '/admin/casino-management/casino-games',
  Countries: '/admin/countries',
  CreateSAdminUser: '/admin/create-admin-user',
  EditSAdminUser: '/admin/edit-admin-user/:adminId',
  TransactionsBanking: '/admin/transactions-banking',
  Deposit: '/admin/deposit',
  Withdraw: '/admin/withdraw',
  Aggregators: '/admin/aggregators',
  CasinoCategory: '/admin/casino-category',
  CasinoSubCategory: '/admin/casino-sub-category',
  RestrictedGames: '/admin/restricted-games/:countryId',
  RestrictedProviders: '/admin/restricted-providers/:countryId',
  RestrictedProviderCountries: '/admin/restrict-providers-countries/:itemId',
  RestrictedGameCountries: '/admin/restrict-games-countries/:itemId',
  CasinoTransactions: '/admin/casino-transactions',
  CreateCMS: '/admin/create-cms',
  EditCMS: '/admin/edit-cms/:cmsPageId',
  WithdrawRequests: '/admin/withdraw-requests',
  FormFields: '/admin/form-fields',
  CreateBonus: '/admin/create-bonus',
  EditBonus: '/admin/edit-bonus/:bonusId',
  Bonus: '/admin/bonus',
  BonusDetail: '/admin/bonus-details/:bonusId',
  CloneBonus: '/admin/clone-bonus/:bonusId',
  KYCLabels: '/admin/kyc-labels',
  Loyalty: '/admin/loyalty-program',
  EmailTemplate: '/admin/email-templates',
  EditEmailTemplate: '/admin/edit-email-template/:emailTemplateId',
  CreateEmailTemplate: '/admin/create-email-template',
  Profile: '/admin/profile',
  ImageGallery: '/admin/image-gallery',
  BannerManagement: '/admin/banner-management',
  GameReorder: '/admin/game-reorder',
  ReorderSubCategory: '/admin/reorder-sub-category',
  ReorderCategory: '/admin/reorder-category',
}

// theme routes
export const CommonRoutes = {
  ForgotPassword: '/forgot-password',
  ResetPassword: '/reset-password',
  Lock: '/lock',
  NotFound: '/404',
  ServerError: '/500'
}
