"use strict";

module.exports = {
  async up(queryInterface, DataTypes) {
    await queryInterface.bulkInsert("themes", [
      {
        theme_name: "folo",
        theme_mode: "dark",
        primary_color: "#856063",
        secondary_color: "#260d0d",
        theme_options: JSON.stringify({
          palette: {
            mode: "dark",
            primary: {
              main: "#856063",
              light_50: "#ff8696",
              light_80: "#ffa0b4",
              light_90: "#ffa9be",
              dark_20: "#b84750",
            },
            secondary: {
              main: "#260d0d",
              light_50: "#ff8696",
              light_90: "#ffa9be",
              dark_20: "#b84750",
            },
          },
          name: "folo",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "foloabcd",
        theme_mode: "light",
        primary_color: "#9285d6",
        secondary_color: "#e5c7d0",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#9285d6",
              light_50: "#dbc8ff",
              light_80: "#ffefff",
              light_90: "#fffdff",
              dark_20: "#756aab",
            },
            secondary: {
              main: "#e5c7d0",
              light_50: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#b79fa6",
              light_80: "#ffffff",
            },
          },
          name: "foloabcd",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "test",
        theme_mode: "light",
        primary_color: "#fb0ed0",
        secondary_color: "#60b0fb",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#fb0ed0",
              light_50: "#ff15ff",
              light_80: "#ff19ff",
              light_90: "#ff1bff",
              dark_20: "#c90ba6",
            },
            secondary: {
              main: "#60b0fb",
              light_50: "#90ffff",
              light_80: "#adffff",
              light_90: "#b6ffff",
              dark_20: "#4d8dc9",
            },
          },
          name: "test",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "folo123",
        theme_mode: "light",
        primary_color: "#97aad3",
        secondary_color: "#FC6065",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#97aad3",
              light_50: "#e3ffff",
              light_80: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#7988a9",
            },
            secondary: {
              main: "#FC6065",
              light_50: "#ff9098",
              light_80: "#ffadb6",
              light_90: "#ffb6c0",
              dark_20: "#ca4d51",
            },
          },
          name: "folo123",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "extro123",
        theme_mode: "light",
        primary_color: "#105AFB",
        secondary_color: "#FC6065",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#105AFB",
              light_50: "#1887ff",
              light_80: "#1da2ff",
              light_90: "#1eabff",
              dark_20: "#0d48c9",
            },
            secondary: {
              main: "#FC6065",
              light_50: "#ff9098",
              light_80: "#ffadb6",
              light_90: "#ffb6c0",
              dark_20: "#ca4d51",
            },
          },
          name: "extro123",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "folo test 123",
        theme_mode: "light",
        primary_color: "#e53847",
        secondary_color: "#d2c6ca",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#e53847",
              light_50: "#ff546b",
              light_80: "#ff6580",
              light_90: "#ff6a87",
              dark_20: "#b72d39",
            },
            secondary: {
              main: "#d2c6ca",
              light_50: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#a89ea2",
              light_80: "#ffffff",
            },
          },
          name: "folo test 123",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "Folo12",
        theme_mode: "dark",
        primary_color: "#e3e566",
        secondary_color: "#544f4f",
        theme_options: JSON.stringify({
          palette: {
            mode: "dark",
            primary: {
              main: "#e3e566",
              light_50: "#ffff99",
              light_80: "#ffffb8",
              light_90: "#ffffc2",
              dark_20: "#b6b752",
            },
            secondary: {
              main: "#544f4f",
              light_50: "#7e7777",
              light_90: "#a09696",
              dark_20: "#433f3f",
              light_80: "#978e8e",
            },
          },
          name: "Folo12",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "Folo123",
        theme_mode: "light",
        primary_color: "#0efb55",
        secondary_color: "#dfa4a6",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#0efb55",
              light_50: "#15ff80",
              light_80: "#19ff99",
              light_90: "#1bffa2",
              dark_20: "#0bc944",
            },
            secondary: {
              main: "#dfa4a6",
              light_50: "#fff6f9",
              light_80: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#b28385",
            },
          },
          name: "Folo123",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "advantage",
        theme_mode: "light",
        primary_color: "#b58790",
        secondary_color: "#e8dee0",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#b58790",
              light_50: "#ffcbd8",
              light_80: "#fff3ff",
              light_90: "#ffffff",
              dark_20: "#916c73",
            },
            secondary: {
              main: "#e8dee0",
              light_50: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#bab2b3",
              light_80: "#ffffff",
            },
          },
          name: "advantage",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "EXtro1234",
        theme_mode: "light",
        primary_color: "#e59776",
        secondary_color: "#ebe6e7",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#e59776",
              light_50: "#ffe3b1",
              light_80: "#ffffd4",
              light_90: "#ffffe0",
              dark_20: "#b7795e",
            },
            secondary: {
              main: "#ebe6e7",
              light_50: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#bcb8b9",
              light_80: "#ffffff",
            },
          },
          name: "EXtro1234",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "test12345",
        theme_mode: "dark",
        primary_color: "#68609a",
        secondary_color: "#FC7E46",
        theme_options: JSON.stringify({
          palette: {
            mode: "dark",
            primary: {
              main: "#68609a",
              light_50: "#9c90e7",
              light_80: "#bbadff",
              light_90: "#c6b6ff",
              dark_20: "#534d7b",
            },
            secondary: {
              main: "#FC7E46",
              light_50: "#ffbd69",
              light_80: "#ffe37e",
              light_90: "#ffef85",
              dark_20: "#ca6538",
            },
          },
          name: "test12345",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "EXpo12",
        theme_mode: "dark",
        primary_color: "#4852d5",
        secondary_color: "#8d6868",
        theme_options: JSON.stringify({
          palette: {
            mode: "dark",
            primary: {
              main: "#4852d5",
              light_50: "#6c7bff",
              light_80: "#8294ff",
              light_90: "#899cff",
              dark_20: "#3a42aa",
            },
            secondary: {
              main: "#8d6868",
              light_50: "#d49c9c",
              light_80: "#febbbb",
              light_90: "#ffc6c6",
              dark_20: "#715353",
            },
          },
          name: "EXpo12",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "Triadic",
        theme_mode: "light",
        primary_color: "#7a3eda",
        secondary_color: "#8ce8b4",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#7a3eda",
              light_50: "#b75dff",
              light_80: "#dc70ff",
              light_90: "#e876ff",
              dark_20: "#6232ae",
            },
            secondary: {
              main: "#8ce8b4",
              light_50: "#d2ffff",
              light_80: "#fcffff",
              light_90: "#ffffff",
              dark_20: "#70ba90",
            },
          },
          name: "Triadic",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "dark",
        theme_mode: "dark",
        primary_color: "#2c91c3",
        secondary_color: "#e5906c",
        theme_options: JSON.stringify({
          palette: {
            mode: "dark",
            primary: {
              main: "#2c91c3",
              light_50: "#42daff",
              light_80: "#4fffff",
              light_90: "#54ffff",
              dark_20: "#23749c",
            },
            secondary: {
              main: "#e5906c",
              light_50: "#ffd8a2",
              light_80: "#ffffc2",
              light_90: "#ffffcd",
              dark_20: "#b77356",
            },
          },
          name: "dark",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "custom test",
        theme_mode: "light",
        primary_color: "#c35d4b",
        secondary_color: "#bb9868",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#c35d4b",
              light_50: "#ff8c71",
              light_80: "#ffa787",
              light_90: "#ffb18f",
              dark_20: "#9c4a3c",
            },
            secondary: {
              main: "#bb9868",
              light_50: "#ffe49c",
              light_80: "#ffffbb",
              light_90: "#ffffc6",
              dark_20: "#967a53",
            },
          },
          name: "custom test",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "new dark",
        theme_mode: "dark",
        primary_color: "#f1f50f",
        secondary_color: "#fd44f7",
        theme_options: JSON.stringify({
          palette: {
            mode: "dark",
            primary: {
              main: "#f1f50f",
              light_50: "#ffff17",
              light_80: "#ffff1b",
              light_90: "#ffff1d",
              dark_20: "#c1c40c",
            },
            secondary: {
              main: "#fd44f7",
              light_50: "#ff66ff",
              light_80: "#ff7aff",
              light_90: "#ff81ff",
              dark_20: "#ca36c6",
            },
          },
          name: "new dark",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "light",
        theme_mode: "light",
        primary_color: "#91ea8b",
        secondary_color: "#b3c6ff",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#91ea8b",
              light_50: "#daffd1",
              light_80: "#fffffa",
              light_90: "#ffffff",
              dark_20: "#74bb6f",
            },
            secondary: {
              main: "#b3c6ff",
              light_50: "#ffffff",
              light_80: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#8f9ecc",
            },
          },
          name: "light",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        theme_name: "test123456",
        theme_mode: "light",
        primary_color: "#59d251",
        secondary_color: "#e6a3b6",
        theme_options: JSON.stringify({
          palette: {
            mode: "light",
            primary: {
              main: "#59d251",
              light_50: "#86ff7a",
              light_80: "#a0ff92",
              light_90: "#a9ff9a",
              dark_20: "#47a841",
            },
            secondary: {
              main: "#e6a3b6",
              light_50: "#fff5ff",
              light_80: "#ffffff",
              light_90: "#ffffff",
              dark_20: "#b88292",
            },
          },
          name: "test123456",
        }),
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, DataTypes) {
    await queryInterface.bulkDelete("themes", null, {});
  },
};
