export const ERRORS = {
  UNAUTHORIZED: "unauthorized",
  FORBIDDEN: "forbidden",
  NOT_FOUND: "notFound",
  METHOD_NOT_ALLOWED: "methodNotAllowed",
  BAD_DATA: "badData",
  BAD_REQUEST: "badRequest",
  INTERNAL: "internal",
  SERVER_ERROR: "serverError",
  SERVER_UNAVAILABLE: "serverUnavailable",
};

export const APP_ERROR_CODES = {
  EMAIL_NOT_REGISTERED: "This email is not registered",
  INCORRECT_PASSWORD: "This password is incorrect",
  SUPERADMIN_NOT_FOUND: "Admin not found",
  ADMIN_NOT_FOUND: "Admin not found",
  AFFILIATE_NOT_FOUND: "Affiliate not found",
  INVALID_TOKEN: "Access token is invalid",
  INACTIVE_ADMIN: "Cannot login, current user is in-active",
};

export const ERROR_MSG = {
  SERVER_ERROR: "Something went wrong",
  EXISTS: "already exists",
  NOT_FOUND: "not found",
  NOT_EXISTS: "does not exists",
  ID_REQUIRED: "ID required",
  bANNER_KEY_REQUIRED: "ID_REQUIRED required",
  EMAIL_EXIST: "Email Address already exist",
  TOGGLE_CASE_ERROR: "Case value invalid",
  NOT_ALLOWED: "Action not allowed",
  FAILED: "failed",
  BALANCE_ERROR: "Insufficient balance",
  CURRENCY_NOT_SUBSET: "Currency should be as per allowed configuration",
  WITHDRAW_STATUS_ERR: "Status already updated",
  WITHDRAW_STATUS_ERR_2: "Status already pending",
  CURRENCY_REQUIRED: "Currency code is required",
  CREATE_ERROR: "Cannot create admin user",
  CREATE_SUPERADMIN_ERROR: "Cannot create SuperAdmin user",
  USERNAME_EXIST: "Username already exists",
  PERMISSION_DENIED: " permission denied",
  TRANSACTION_DENIED: "Receiver not in hierarchy, transaction denied",
  ADMIN_TO_USER: "Receiver user not in hierarchy, transaction denied",
  ADMIN_TO_ADMIN: "Receiver admin not in hierarchy, transaction denied",
  DAILY_LIMIT_NOT_FOUND: "Set daily limit first to create site",
  DAILY_LIMIT_NOT_FOUND_SITE: "Daily limit not set by superadmin",
  MAX_DAILY_LIMIT: "Max daily limit for this currency is ",
  ORDER_ERROR: "Send order for all sub categories.",
  SENDGRID_ERROR: "Unable to send email.",
  REASON_REQUIRED: "Reason is required to mark user in-active.",
  ELASTIC_CONNECTION: "Unable to fetch data from elastic",
  CUSTOM_DATES_REQUIRED: "Custom date options required dates",
  WAGERING_TYPE: "Invalid wagering type selected.",
  LOYALTY_LEVEL_NOT_FOUND: "Loyalty level settings not found",
  BONUS_ISSUE: "Bonus cannot be issued.",
  BONUS_DELETE: "Bonus cannot be deleted, issuer is different.",
  BONUS_PENDING: "Bonus cannot be deleted, already activated by user.",
  BONUS_AVAIL: "Bonus cannot be activated, try again later",
  EXTERNAL_API_ERROR: "External api response error",
  SPINS_QUANTITY: "Spins quantity must be less than 100",
  SPINS_VALIDITY: "Days to clear should be less than 30",
  DELETE_PRIMARY_EMAIL: "Cannot delete primary Email",
  SENDGRID_CREDENTIALS: "Sendgrid credentials not found",
  PRIMARY_TEMPLATE_ERROR: "Select other primary template",
  EMPTY_GALLERY: "Image gallery empty",
  CREDENTIALS_NOT_FOUND: "Send Grid credentials not found",
  LANGUAGE_NOT_SUBSET: "Language should be as per allowed configuration",
  REMOVE_MONEY: "Remove money amount is more than wallet balance",
  ELASTIC_DOWN: "Elastic cluster is down !!",
};
